language: python
python:
- "2.7"
addons:
  apt:
    packages:
    - djvulibre-bin
    - libdjvulibre-dev
    - libxml2-utils
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

before_install:
# add for profile
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- export PATH="/usr/lib/ccache:$PATH"
- pip install --build build-cython cython
- pip install python-djvulibre
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install argparse; fi
- pip install --build build-lxml lxml
- pip install pyicu
- pip install html5lib
- pip install --build build-pillow pillow

# add for profile
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"
 - pip install nose-cprof
 - pip install properform


script:
- nosetests --all --verbose --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_ocrodjvu_fb4aa9c054_4
  - python -m properform Push 47.88.50.110:15554 asdf_ocrodjvu_fb4aa9c054_4 ./profile_ocrodjvu_fb4aa9c054_4

- xmllint --noout --valid doc/*.xml

# vim:ts=2 sts=2 sw=2 et
 #2017-08-14 14:51:57 modified at 0 #2017-08-14 14:52:01 modified at 1 #2017-08-14 14:52:05 modified at 2 #2017-08-14 14:52:09 modified at 3 #2017-08-14 14:52:14 modified at 4