language: python
python:
- "2.7"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libdjvulibre-dev djvulibre-bin

# add for profile
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq


install:
- pip install cython
- pip install python-djvulibre
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install argparse; fi
- pip install lxml
- pip install pyicu
- pip install html5lib
- pip install pillow

# add for profile
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"
- pip install nose-cprof
- pip install properform

script:
- nosetests --all --verbose --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_ocrodjvu_2095c9d5cb_0
- python -m properform Push 47.88.50.110:15554 asdf_ocrodjvu_2095c9d5cb_0 ./profile_ocrodjvu_2095c9d5cb_0


# vim:ts=2 sts=2 sw=2 et
 #2017-08-14 14:55:14 modified at 0